# Generated by Django 4.2.9 on 2024-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dailyupdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("basecurr", models.CharField(max_length=200)),
                ("targetcurr", models.CharField(max_length=200)),
                ("rates", models.IntegerField(max_length=50)),
            ],
        ),
    ]
