# Generated by Django 4.2.9 on 2024-01-10 19:17

import convertor_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="old_user", max_length=50, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            convertor_app.models.valid_email,
                            django.core.validators.EmailValidator(
                                message="enter a valid email"
                            ),
                        ],
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        null=True, validators=[convertor_app.models.validate_age]
                    ),
                ),
                (
                    "joining_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dailyupdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("basecurr", models.CharField(max_length=20)),
                ("targetcurr", models.CharField(max_length=20)),
                ("rates", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="convertor_app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user conversions",
                "ordering": ["date"],
            },
        ),
    ]
