# Generated by Django 4.2.9 on 2024-01-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convertor_app", "0002_alter_dailyupdate_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyupdate",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
